### ISSUE TITLE
Help please - having problems getting this to work

### ISSUE THREAD

**Issue by jacqui932** [studds/nx-aws#1]
Hi,

This library looks like a perfect fit for a project I am working on at the moment.  However, I am finding it hard to get it to work in my project.  I am currently getting this error when running a test from the API Gateway:

Endpoint response body before transformations: {"errorMessage":"Cannot find module 'source-map-support/register'","errorType":"Error","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)","Object.source-map-support/register (/var/task/lambda.js:2559:18)","__webpack_require__ (/var/task/lambda.js:20:30)","Object../node_modules/@nx-aws/sam/src/build/source-map-install.js (/var/task/lambda.js:2424:1)","__webpack_require__ (/var/task/lambda.js:20:30)","Object.0 (/var/task/lambda.js:2436:1)","__webpack_require__ (/var/task/lambda.js:20:30)"]}
Tue Sep 03 08:02:11 UTC 2019 : Lambda execution failed with status 200 due to customer function error: Cannot find module 'source-map-support/register'. Lambda request id: 1317e79e-6606-4c96-a7ac-c96058d42101
Tue Sep 03 08:02:11 UTC 2019 : Method completed with status: 502

Template.yaml:

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with nestjs.

Resources:
  LambdaNestJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      # This is the name of the handler file and then the name of the exported handler function
      # (standard SAM approach)
      Handler: lambda.handler
      Runtime: nodejs8.10
      # CodeUri should be the directory, relative to template.yaml, where the handler file is found
      CodeUri: src/app
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

lambda.ts:

require('source-map-support').install();

import { Context, Handler } from 'aws-lambda';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { Server } from 'http';
import { createServer, proxy } from 'aws-serverless-express';
import { eventContext } from 'aws-serverless-express/middleware';
// @ts-ignore
import express from 'express';

let cachedServer: Server;
const expressApp = require('express')();

// NOTE: If you get ERR_CONTENT_DECODING_FAILED in your browser, this is likely
// due to a compressed response (e.g. gzip) which has not been handled correctly
// by aws-serverless-express and/or API Gateway. Add the necessary MIME types to
// binaryMimeTypes below
const binaryMimeTypes: string[] = [];

async function bootstrapServer(): Promise<Server> {
  const nestApp = await NestFactory.create(AppModule, expressApp);
  nestApp.use(eventContext());
  await nestApp.init();
  return createServer(expressApp, undefined, binaryMimeTypes);
}

export const handler: Handler = async (event: any, context: Context) => {
  if (!cachedServer) {
    console.log('Bootstraping server');
    cachedServer = await bootstrapServer();
  } else {
    console.log('Using cached server');
  }
  return proxy(cachedServer, event, context, 'PROMISE').promise;
};

btw., It would be fantastic if there was a small working nx app with a nestjs back end app and a dummy angular front end app showing this library in action.

Many thanks for any help you could provide.

**Comment by studds** [comment]
Hey there, did you get this working? Are you able to provide a small repository with a reproduction? Thanks for the feedback re: an example app, I'll look into that.

**Comment by jacqui932** [comment]
Hi - sorry I gave up with this in the end.  I am very new to NX and Nest JS in general and don't know enough to get this working.  I came up with a horrible hacky way to get the code deployed to AWS in the end which I am ashamed of so I am still very interested in the example app if that is at all possible.

**Comment by studds** [comment]
@jacqui932 apologies for the really delayed reply, this is not designed to work with Nest, see https://nx.dev/angular/plugins/nest/overview#nest-plugin for that.

I've added an example app for using nx-aws with [AWS SAM](https://aws.amazon.com/serverless/sam/): https://github.com/studds/nx-aws-example

**Comment by jacqui932** [comment]
Hi @studds - no probs.  Thank you for the pointer to nest-plugin and I will check out your example app too :-)
