### ISSUE TITLE
Cannot find module '@nrwl/workspace/src/utilities/create-package-json'

### ISSUE THREAD

**Issue by maxime1992** [studds/nx-aws#108]
I get the error in the title after an nx upgrade, here are the deps I've got:

```
"@nrwl/workspace": "15.3.0",
"@nx-aws/sam": "0.15.1",
```

**Comment by maxime1992** [comment]
Had a look, looks like they've moved the file: https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/create-package-json.ts

I'll raise a PR

**Comment by studds** [comment]
This is resolved and released as 0.15.2 😄
