### ISSUE TITLE
Required property 's3Bucket' is missing

### ISSUE THREAD

**Issue by ChristopherPHolder** [studds/nx-aws#114]
First of all love the project <3

So have project with two sam apps and I want to move them into NX. 

Your plugin seems like an awesome way to do that. So as i'm trying it out I feel like the docs are missing some getting started sections. 

If I simple try installing it and generating an app, then deploying it I get this error. 

> Required property 's3Bucket' is missing

As so don't really know where to look, what `s3Bucket` config was I suppose to have and where should I put it? 

https://github.com/ChristopherPHolder/ufo/pull/30 

Is there something more I need to do for the set up? 

Im happy to contribute with the docs so make easer for the next person :)

**Comment by studds** [comment]
Absolutely, I've added some extra documentation around this in this PR: https://github.com/studds/nx-aws/pull/115

Let me know if that addresses your query, and if you have any other issues along the way, call them out, and I'll do my best to respond ASAP.

The ideal solution would be to create / prompt for this bucket when generating projects... if anyone wants to take that on, that would be fab 😄
