### ISSUE TITLE
@nx-aws/core dependency missing

### ISSUE THREAD

**Issue by nhammond101** [studds/nx-aws#42]
when trying to deploy, I got an error message about the missing dependency `@nx-aws/core`.  Should this be bundled as a dependency or peer dependency?  my guess would be dependency but would prefer @studds's input before raising a PR

**Comment by studds** [comment]
Hey @nhammond101, yeah, there's probably an argument it should be a dependency. Leave it with me.

**Comment by studds** [comment]
Thanks for raising this - I've made that change in v0.6.2
