### ISSUE TITLE
Skip pull image

### ISSUE THREAD

**Issue by vespertilian** [studds/nx-aws#52]
When running sam via `execute` it's loads faster if we skip pulling the image.

I hardcoded it in my repo... thinking it would be nice to have as an option, as I guess you sometimes want to pull the image. 

Maybe something like: 

`nx serve api --skip-pull-image`

```
const args = [
            'local',
            'start-api',
            '--template',
            templatePath,
            '--skip-pull-image'
        ]
```

Not sure the best place... way to do this. What do you think?

**Comment by studds** [comment]
Have you tried using the `args` option in your `angular.json` / `workspace.json`:

```
    ...
    "serve": {
        "builder": "@nx-aws/sam:execute",
        "options": {
            "buildTarget": "api:build",
            "packageTarget": "api:package",
            "args": ["--skip-pull-image"]
        },
        "configurations": {
            "production": {}
        }
    },
    ...
```

**Comment by vespertilian** [comment]
Works great  :sunglasses:

Thanks again for all your hard work on this.
