### ISSUE TITLE
Same function file is built twice

### ISSUE THREAD

**Issue by vespertilian** [studds/nx-aws#54]
As you can see in this image if you add a second function to the template.yaml when it builds it seems to still build the first function. Pull down this copy of your sample app and build the API to replicate. https://github.com/vespertilian/nx-aws-example

<img width="1210" alt="hello-in-auth-file" src="https://user-images.githubusercontent.com/441418/101321893-3c334e80-38ba-11eb-94f9-5e41c2bed1f3.png">

**Comment by studds** [comment]
I couldn't reproduce this as explained.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/3046407/101408526-a4247c00-3930-11eb-88a9-65d714badf75.png">

Of note, this currently doesn't remove build directories between builds, which it really ought to do. I suspect the steps are as follows:

1. Copy the directory, but not rename hello.ts
2. Add to template.yaml
3. Build
4. Rename hello.ts to auth.ts and update template.yaml accordingly
5. Build

Can you confirm? If so, we can update this issue accordingly.

**Comment by vespertilian** [comment]
@studds So I deleted the directory manually and it still happened. Maybe NX or TS is caching some config. As we are going to jump on a call I will show it to you then.

**Comment by studds** [comment]
@vespertilian it could be nx cache containing the wrong output, after the steps indicated above - try deleting the directory and then running `nx build api --skipNxCache`

**Comment by vespertilian** [comment]
@studds I think your right, that it might be an old cached version
