### ISSUE TITLE
Move to AWS SDK v3

### ISSUE THREAD

**Issue by vespertilian** [studds/nx-aws#74]
I have been working on setting up multiple environments for my app and locally I was trying to use AWS SSO which is a bit more secure as you do not keep credentials on your machine. 

However, I am getting an error: 
`Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1`

I don't think the V2 SDK supports SSO. 
https://github.com/aws/aws-sdk-js-v3/issues/1158

Are you good for a PR to update this?

**Comment by studds** [comment]
Yep, love one

**Comment by vespertilian** [comment]
So, 

Looking into this some more. I think I just needed to update my version of the `aws-sdk`. The v3 of the SDK just breaks out all the libraries. However, SSO does not seem to work fully with either yet. So I will leave this for now.
