### ISSUE TITLE
build aws sam incompatible with nx 12

### ISSUE THREAD

**Issue by guiseek** [studds/nx-aws#91]
Hello how are you?

Do you have any plans to work on the migration to nx 12? I confess that I tried to make it and send it as a contributing, but I was unsuccessful. This library is awesome and it would be great to keep it. I hope to help more in another opportunity.

#### this is the error when using with nx 12 version
```
Running build for entry app/hello/hello
Cannot read property 'length' of undefined

———————————————————————————————————————————————

>  NX   ERROR  Running target "build" failed
```

**Comment by studds** [comment]
Hey @guiseek, I haven't had the time I would've liked to dedicate to this library recently. Following this prompter, I've sat down to push out an update. I haven't been able to test it thoroughly, other than a very quick test on the example repo, so I've published v0.13.0 under the "next" tag. You can install via:

```
yarn add -D @nx-aws/sam@next @nx-aws/core@next @nx-aws/s3@next
```

or

```
npm i -D @nx-aws/sam@next @nx-aws/core@next @nx-aws/s3@next
```

Let me know how you go. Any issues, let me know here. Once I've had a chance to test a bit more, I'll publish to latest.

**Comment by studds** [comment]
I'm hoping to have a bit more time to spend on this in late September.

**Comment by guiseek** [comment]
I think you solved the problem @studds! I tested it quickly at lunchtime and the build is working, tonight I will run the deploy with more details.

thank you very much for the quick attention and solution!

**Comment by guiseek** [comment]
> I'm hoping to have a bit more time to spend on this in late September.

@studds forgive me for not returning sooner, it is working very well and I am very grateful for your immediate attention!
we can close this issue, thank you very much!
